;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Data.Damage",NewTagName="Data.StaminaUsed")
+GameplayTagRedirects=(OldTagName="Player.State.AnimEnd",NewTagName="Event.AnimEnd")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.StaminaUsed",DevComment="")
+GameplayTagList=(Tag="Event.AnimEnd",DevComment="")
+GameplayTagList=(Tag="Event.DodgeEnd",DevComment="")
+GameplayTagList=(Tag="Event.PushTrigger",DevComment="")
+GameplayTagList=(Tag="Player.State.Dodge",DevComment="")
+GameplayTagList=(Tag="Player.State.UsingAbility",DevComment="")

